[package]
name = "vizia"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A Rust GUI Framework"
autoexamples = false
rust-version = "1.60"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["core", "winit", "baseview", "derive", "run-wasm"]

[[example]]
name = "action_modifier"
path = "examples/action_modifier.rs"

[[example]]
name = "animation"
path = "examples/animation.rs"

[[example]]
name = "basic"
path = "examples/basic.rs"

[[example]]
name = "binding"
path = "examples/binding.rs"

[[example]]
name = "compose"
path = "examples/compose.rs"

[[example]]
name = "counter"
path = "examples/counter.rs"

[[example]]
name = "cursor_icon"
path = "examples/cursor_icon.rs"

[[example]]
name = "l10n"
path = "examples/l10n.rs"

[[example]]
name = "local_binding"
path = "examples/local_binding.rs"

[[example]]
name = "local_data"
path = "examples/local_data.rs"

[[example]]
name = "long_list"
path = "examples/long_list.rs"

[[example]]
name = "modal"
path = "examples/modal.rs"

[[example]]
name = "more_knobs"
path = "examples/more_knobs.rs"

[[example]]
name = "multiple_binding"
path = "examples/multiple_binding.rs"

[[example]]
name = "overflow"
path = "examples/overflow.rs"

[[example]]
name = "proxy"
path = "examples/proxy.rs"

[[example]]
name = "scrollview"
path = "examples/scrollview.rs"

[[example]]
name = "state"
path = "examples/state.rs"

[[example]]
name = "stylesheet"
path = "examples/stylesheet.rs"

[[example]]
name = "styling"
path = "examples/styling.rs"

[[example]]
name = "table"
path = "examples/table.rs"

[[example]]
name = "textbox_list"
path = "examples/textbox_list.rs"

[[example]]
name = "transform"
path = "examples/transform.rs"


[[example]]
name = "button"
path = "examples/controls/button.rs"

[[example]]
name = "slider"
path = "examples/controls/slider.rs"

[[example]]
name = "knob"
path = "examples/controls/knob.rs"

[[example]]
name = "checkbox"
path = "examples/controls/checkbox.rs"

[[example]]
name = "radiobutton"
path = "examples/controls/radiobutton.rs"

[[example]]
name = "zstack"
path = "examples/controls/zstack.rs"

[[example]]
name = "popup"
path = "examples/controls/popup.rs"

[[example]]
name = "dropdown"
path = "examples/controls/dropdown.rs"

[[example]]
name = "textbox"
path = "examples/controls/textbox.rs"

[[example]]
name = "number_input"
path = "examples/controls/number_input.rs"

[[example]]
name = "widget_gallery"
path = "examples/controls/widget_gallery.rs"

[[example]]
name = "list"
path = "examples/lists/list.rs"

[[example]]
name = "selectable_list"
path = "examples/lists/selectable_list.rs"

[[example]]
name = "editable_list"
path = "examples/lists/editable_list.rs"

[[example]]
name = "multiselectable_list"
path = "examples/lists/multiselectable_list.rs"

[[example]]
name = "sortable_list"
path = "examples/lists/sortable_list.rs"

[[example]]
name = "static_list"
path = "examples/lists/static_list.rs"

[[example]]
name = "image"
path = "examples/controls/image.rs"

[[example]]
name = "menu"
path = "examples/controls/menu.rs"


[[example]]
name = "7guis_counter"
path = "examples/7GUIs/counter.rs"

[[example]]
name = "7guis_temperature_converter"
path = "examples/7GUIs/temperature_converter.rs"

[[example]]
name = "7guis_flight_booker"
path = "examples/7GUIs/flight_booker.rs"

[[example]]
name = "7guis_crud"
path = "examples/7GUIs/crud.rs"

[[example]]
name = "focus_order"
path = "examples/accessibility/focus_order.rs"

[features]
default = ["winit", "clipboard", "x11", "wayland"]
clipboard = ["vizia_core/clipboard"]
winit = ["vizia_winit"]
baseview = ["vizia_baseview"]
meadowlark = ["winit", "vizia_core/meadowlark"]
x11 = ["vizia_winit?/x11", "vizia_core/x11"]
wayland = ["vizia_winit?/wayland", "vizia_core/wayland"]

[dependencies]
vizia_core = { version = "0.1.0", path = "core"}
vizia_winit = { version = "0.1.0", path = "winit", optional = true }
vizia_baseview = { version = "0.1.0", path = "baseview", optional = true }

[dev-dependencies]
english-numbers = "0.3.3"
lazy_static = "1.4.0"
chrono = "0.4.19"
image = { version = "0.24.0", default-features = false, features = ["png"] }
reqwest = { version = "0.11.9", features = ["blocking"] }
instant = "0.1.12"
